import dbasehandler as dbh
handler = dbh.DbHandler()
handler.setup_session()
#handler.populate_metabase_collections()
analyzer = dbh.ResultsAnalyzer(handler)
analyzer.main()
#handler.dbInit()
#handler.populate_runs_all()
#handler.guesses_exhaustive()
#handler.populate_learning_curves()
#handler.guesses_sampling()
#handler.guesses_active()
#handler.populate_results()
